# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: unit-tests

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  tests:
    runs-on: ubuntu-latest    
    permissions:
      contents: read
      packages: read
    env:
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        registry-url: https://npm.pkg.github.com/

    - name: nftProviders tests
      run: |
        yarn install
        yarn test
      working-directory: ./packages/nftProviders

    - name: oortApiClient tests
      run: |
        yarn install
        yarn test
      working-directory: ./packages/oortApiClient

    - name: ui tests
      run: |
        yarn install
        yarn test
      working-directory: ./packages/ui

    - name: urlSearchParams tests
      run: |
        yarn install
        yarn test
      working-directory: ./packages/urlSearchParams

    - name: web3Connectors tests
      run: |
        yarn install
        yarn test
      working-directory: ./packages/web3Connectors
    