# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: unit-tests

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  tests:

    runs-on: ubuntu-latest    
    defaults:
      run:
        working-directory: ./packages/

    permissions:
      contents: read
      packages: read
    env:
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        registry-url: https://npm.pkg.github.com/

    - name: nftProviders tests
      run: |
        yarn install
        yarn test
      working-directory: ./app